# Site settings
title: A Faithful Witness
email: info@afaithfulwitness.org
description: "This site contains the letter of warning issued by the co-workers in the Lord's recovery and related materials concerning the teachings and practices promoted by Brother Dong Yu Lan and his co-workers. "
baseurl: "/faithful-witness"
url: "http://afaithfulwitness.org"

# static file storage
pdf: "/pdf"
audio: "/mp3"
video: "/video"

# Build settings
markdown: kramdown
permalink: pretty


# collections
collections:
    annotations:
        output: true
